"""initial migration

Revision ID: 3fedd7c92223
Revises: 
Create Date: 2021-02-08 07:38:55.067659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fedd7c92223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_users'))
    )
    op.create_table('active_user',
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['users.name'], name=op.f('fk_active_user_name_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_active_user'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], name=op.f('fk_categories_user_name_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_name', 'name', name='user-category-uc')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('descr', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_bills_category_id_categories'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], name=op.f('fk_bills_user_name_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('categories')
    op.drop_table('active_user')
    op.drop_table('users')
    # ### end Alembic commands ###
